### ISSUE TITLE
Error loading on pharo8x64 on mac 

### ISSUE THREAD

**Issue by akevalion** [medicka/PharoGSoC#1]
I have executed this on a fresh pharo8 64bits image on mac.10.14.5 

![image](https://user-images.githubusercontent.com/10532890/60469637-727f8f80-9c2b-11e9-9517-1808008bee35.png)

This class is missing `TVertexTrait`

**Comment by jecisc** [comment]
I see a dependency problem. I'll see tomorrow with Nina to fix it.
