### ISSUE TITLE
GraphStructure posible rename

### ISSUE THREAD

**Issue by akevalion** [medicka/PharoGSoC#6]
It would be nice that GraphStruture can be renamed to GraphLayout-Structure, In order to see all the packages of this project in the system browser.

![image](https://user-images.githubusercontent.com/10532890/63512739-cf3d4f00-c4e4-11e9-8887-472a5b9f45ff.png)

In the previous picture, I can not see package `GraphLayout`

**Comment by medicka** [comment]
You can see both of them when you search just with "graph". In your picture you typed "GraphSt", that is why it is not showing the layouts as well.
